### ISSUE TITLE
403 и 404

### ISSUE THREAD

**Issue by Chuvil** [romannik007/docker-bitrix-new#1]
Windows 10 c WSL 2.
После распаковки архивов и на моменте перехода к этапу восстановления БД выдало ошибку 403 - доступ запрещен - на все файлы. После перезагрузки ПК выдаёт 404.
Что делать с этим?

**Comment by romannik007** [comment]
> Windows 10 c WSL 2. После распаковки архивов и на моменте перехода к этапу восстановления БД выдало ошибку 403 - доступ запрещен - на все файлы. После перезагрузки ПК выдаёт 404. Что делать с этим?

этот проект я не тестировал на винде
этот проект новее: https://github.com/romannik007/docker-bitrix-new-test - под винду 9 пункт. Сделал доступ к файлам битрикс через вебдав, не пробрасывая волум на хост из-за медленной работы, в частности установки и распаковки бэкап
